version: "3"

services:
  common: &COMMON
    build:
      context: .
    environment:
      - AMQP_HOST=secure-rabbitmq
      - AMQP_PORT=5673
      - USERNAME=test
      - PASSWORD=test
    depends_on:
      - secure-rabbitmq
    ports:
      - 127.0.0.1:3000:3000
  dev:
    <<: *COMMON
    command: node dist/main.js

  rabbitmq:
    image: rabbitmq:3-management
    ports: 
      - 15672:15672
      - 5672:5672
  secure-rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 15673:15672
      - 5673:5672
    environment: 
        RABBITMQ_DEFAULT_PASS: "test"
        RABBITMQ_DEFAULT_USER: "test"
