version: "3"

services:
  common: &COMMON
    build:
      context: .
    links:
      - mongodb:mongo.local
    ports:
      - 127.0.0.1:3000:3000
  dev:
    <<: *COMMON
    command: node dist/main.js

  mongodb:
    image: mongo:latest
    environment:
      - MONGODB_DATABASE="apartments-scraper-test"
    ports:
      - 27017:27017